# Generated by Django 5.0.6 on 2024-09-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udus_lost_and_found', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundreport',
            name='address',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='foundreport',
            name='gsm',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='foundreport',
            name='item',
            field=models.CharField(default='Unknown Item', max_length=255),
        ),
    ]
