version: 1
services:
  - type: web
    name: my-django-app
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn mylostandfound.wsgi --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mylostandfound.settings
      - key: PORT
        value: "10000"
    routes:
      - type: rewrite
        source: "/static/*"
        destination: "/static/$1"