services:
  - type: web
    name: udus-lost-and-found
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn mylostandfound.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "https://udus-lost-and-found.onrender.com"
    staticPublishPath: staticfiles